

server:
  port: 9090
myyml:
  string: hello,yml


# 连接数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb?characterEncoding=utf8mb4&useSSL=true
    name: root
    password: 123



mystring1: hello\nword
mystring2: 'hello\nword'
mystring3: "hello\\nword"


# 对象写法 1：
student:
  id: 1
  name: 张三
  age: 20

# 对象写法 2：⾏内写法（与上⾯的写法作⽤⼀致）
student2: {id: 2,name: 李四,age: 20}



# 集合写法 1：
dbtypes:
name:
  - mysql
  - sqlserver
  - db2

# 集合写法 2：⾏内写法（与上⾯的写法作⽤⼀致）
dbtype: {name: [mysql,sqlserver,db2]}
